SIAT-Python-Project/KBO-Match-Result-Mail-System

src/webdriver/MyWebDriver.py

MyWebDriver.py 만들었습니다.
이제 이걸 사용해서 각자 크롤링을 해봐요~
아마도 잘 작동하는데 문제 생기면 장희권한테 알려주시면 해결해드릴게요

✨feat: Add #1 MyWebDriver.py

---

src/utils/SleepTime.py

함수 호출 후 잠시 쉬어가는 decorator를 만들었습니다.
문제가 생기면 이슈로 알려주세요!

✨feat: Add #3 SleepTime.py

---

src/webdriver/MyWebDriver.py

MyWebDriver에 SleepTime Decorator를 추가하였습니다.
이제 driverOpen, clickBtn함수를 호출 후 2초 동안 sleep에 빠집니다.

✨feat: Add #5 SleepTime Decorator

---

src/domain/Pitcher.py
src/webdriver/crawling/PitcherCrawler.py

투수 정보를 크롤링했습니다.
Pitcher class는 추후에 바뀔 수 있어용

✨feat: Add #9 PitcherCrawler.py, Pitcher.py

---

src/webdriver/crawling/HitterCrawler.py

페이지가 1개인 경우 처음으로, 마지막으로 버튼이 검색이 안 되어 NoSuchElementException가 발생하는 버그 해결

🐛fix: Apply  #11 try-except to HitterCrawler.py

---

src/domain/Hitter.py
src/domain/Pitcher.py
src/webdriver/crawling/HitterCrawler.py
src/webdriver/crawling/PitcherCrawler.py
src/webdriver/crawling/PlayerCrawler.py

PlayerCrawler를 추가하여 기존 코드에서 HitterCrawler와 PitcherCrawler의 코드 중복을 없앴습니다,

🎨refactor: Add PlayerCrawler.py

---

src/domain/Hitter.py
src/domain/Pitcher.py
src/webdriver/crawling/HitterCrawler.py
src/webdriver/crawling/PitcherCrawler.py
src/webdriver/crawling/PlayerCrawler.py

AVG로 조회시 모든 선수가 조회 안 되는 오류 수정!!!!!

✨feat: #17 AVG로 조회시 모든 선수가 조회 안 되는 버그 수정

---

src/domain/Hitter.py
src/domain/Pitcher.py
src/utils/PlayerSort.py
src/webdriver/crawling/HitterCrawler.py

✨feature/players rank/#16

---

src/webdriver/crawling/TeamRankCrawler.py

함수로 만들었는데 함수가 너무 많아요....
함수가 많음 시간있으면 고칠게요...

✨Feture/team rank crawler/#15

---

src/webdriver/crawling/Scraper.py
src/webdriver/crawling/T_Game

오늘 경기 일정 크롤링 하였습니다.
아예 클래스에서 메소드 합쳐 버려서 함수로 따로 정의해야 할 수도?

feat: Add #20 Scraper.py, T_Game

---

src/webdriver/crawling/T_Game.py
src/webdriver/crawling/Y_Game.py

T_Game 파일 .py 확장자 실종되어 다시 commit 및 Y_Game 경기 전날 크롤링 Add
아예 클래스에서 메소드 합쳐 버려서 함수로 따로 정의해야 할 수도?

✨feat, 🐛fix: Add #24 Y_Game.py, refactor T_Game error to .py 파일 확장자 빼먹음

---

src/webdriver/crawling/T_Game.py
src/webdriver/crawling/Y_Game.py

- 파일 생성 시 루트 폴더로 관리
- T_Game.py and Y_Game.py run() 메소드 생성

✨feat: update #28 T_Game.py Y_Game.py refactoring

---

src/webdriver/crawling/NewsCrawler.py

어제 경기가 없어서 이틀 전으로 설정 했습니다 다시 수정 하겠습니다

feat: Init #30 create NewsCrawler.py

---

src/webdriver/crawling/NewsCrawler.py

🔨fix: Init #30 NewsCrawler.py 어제 날짜 수정

---

src/webdriver/crawling/TeamRankCrawler.py

하나씩 가져오던 데이터를 목차 한 묶음으로 가져오고 list로 반환
클래스로 다시 변수들 선언 후 클래스에서 변수 가져오기

🎨Fix/team rank crawler/#15

---

src/webdriver/crawling/T_GameCrawler.py
src/webdriver/crawling/Y_GameCrawler.py

T_GameCrawler.py run 메소드에서 list[T_Game]을 반환할 수 있도록 함.
Y_GameCrawler.py run 메소드에서 list[Y_Game]을 반환할 수 있도록 함.

✨feat: update #37 T_GameCrawler.py Y_GameCrawler.py refactoring

---

src/webdriver/crawling/TeamRankCrawler.py

🔨 update: Init #15 TeamRankCrawler.py 팀 순위와 목차 리스트 형식으로 반환 및 string형태로 반환

---

src/domain/News.py
src/webdriver/crawling/NewsCrawler.py

✨ update: Init #30 News.py 클래스 생성 및 리스트로 반환

---

src/controller/KBOController.py
src/controller/PlayerController.py
src/domain/Hitter.py
src/domain/Pitcher.py
src/main.py
src/utils/HTMLChanger.py
src/utils/Mail.py
src/view/InputView.py

✨Feature/main/#26

---

src/domain/TeamRank.py
src/webdriver/crawling/TeamRankCrawler.py

xupdate #15 TeamRankCrawler.py 클래스화

---

src/domain/ScoreBox.py
src/webdriver/crawling/ScoreBoxCrawler.py

✨Create: SCORE/BOX 박스스코어박스 크롤링

---

src/main.py

✨feat: #26 main.py 테스트 코드 수정

---

README.md

- [x[ 기능 추가 ✨
README.md를 작성했습니다.

✨docs: #51 README.md 작성
